apiVersion: batch/v1
kind: Job
metadata:
  name: agrius-gut-follower-counts
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: agrius-gut-follower-counts
        image: nandanrao/agrius-gut:latest
        resources:
          requests:
            cpu: 250m
            memory: "512Mi"
        args:
        - python
        - main.py
        - follower-counts
        - ""
        envFrom:
        - secretRef:
            name: agrius-gut-envs
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/usr/share/keys/key.json"
          - name: GOOGLE_PROJECT_ID
            value: "toixotoixo"
          - name: GOOGLE_PUBSUB_SUBSCRIPTION
            value: "agrius-test-belly"
          - name: BELLY_LOCATION
            value: "agrius-tweethouse"
          - name: GUT_LOCATION
            value: "agrius-outputs"
          - name: SPREADSHEET_NAME
            value: "Agrius_search_criteria"
          - name: GUT_END_DATE
            value: "2019-5-20"
        volumeMounts:
          - name: keys
            mountPath: /usr/share/keys
            readOnly: true
      volumes:
        - name: keys
          secret:
            secretName: agrius-gut-keys
